import type {
  User,
  Solution,
  AuditLog,
  ValidationReport,
  Review,
} from "./types"

export const mockUsers: User[] = [
  {
    id: "u1",
    fullName: "Alex Rivera",
    email: "alex@acme.com",
    role: "user",
    organization: "Acme Corp",
    techStack: ["React", "Node.js", "TypeScript"],
    createdAt: "2025-10-15T08:00:00Z",
  },
  {
    id: "u2",
    fullName: "Jordan Chen",
    email: "jordan@techco.com",
    role: "user",
    organization: "TechCo",
    techStack: ["Python", "Django", "PostgreSQL"],
    createdAt: "2025-11-01T10:30:00Z",
  },
  {
    id: "e1",
    fullName: "Dr. Sarah Kim",
    email: "sarah@platform.io",
    role: "expert",
    organization: "Platform Inc",
    techStack: ["React", "Go", "Kubernetes"],
    createdAt: "2025-08-01T09:00:00Z",
  },
  {
    id: "e2",
    fullName: "Marcus Thompson",
    email: "marcus@platform.io",
    role: "expert",
    organization: "Platform Inc",
    techStack: ["Python", "AWS", "Docker"],
    createdAt: "2025-08-15T11:00:00Z",
  },
  {
    id: "a1",
    fullName: "Priya Patel",
    email: "priya@platform.io",
    role: "admin",
    organization: "Platform Inc",
    techStack: [],
    createdAt: "2025-07-01T08:00:00Z",
  },
]

const validationReports: Record<string, ValidationReport> = {
  vr1: {
    id: "vr1",
    solutionId: "s1",
    score: 92,
    checks: [
      { id: "c1", name: "Structure Validation", description: "Validates project directory structure and entry points", status: "pass" },
      { id: "c2", name: "Dependency Check", description: "Checks for outdated or vulnerable dependencies", status: "pass" },
      { id: "c3", name: "Secret Scan", description: "Scans for hardcoded secrets and credentials", status: "pass" },
      { id: "c4", name: "Environment Validation", description: "Validates environment configuration and variables", status: "pass" },
    ],
    completedAt: "2026-01-15T14:30:00Z",
  },
  vr2: {
    id: "vr2",
    solutionId: "s2",
    score: 78,
    checks: [
      { id: "c5", name: "Structure Validation", description: "Validates project directory structure and entry points", status: "pass" },
      { id: "c6", name: "Dependency Check", description: "Checks for outdated or vulnerable dependencies", status: "pass" },
      { id: "c7", name: "Secret Scan", description: "Scans for hardcoded secrets and credentials", status: "fail", details: "Potential API key found in config.ts" },
      { id: "c8", name: "Environment Validation", description: "Validates environment configuration and variables", status: "pass" },
    ],
    completedAt: "2026-01-20T10:15:00Z",
  },
  vr3: {
    id: "vr3",
    solutionId: "s3",
    score: 55,
    checks: [
      { id: "c9", name: "Structure Validation", description: "Validates project directory structure and entry points", status: "fail", details: "Missing entry point file" },
      { id: "c10", name: "Dependency Check", description: "Checks for outdated or vulnerable dependencies", status: "fail", details: "3 critical vulnerabilities found" },
      { id: "c11", name: "Secret Scan", description: "Scans for hardcoded secrets and credentials", status: "pass" },
      { id: "c12", name: "Environment Validation", description: "Validates environment configuration and variables", status: "fail", details: "Missing required env variables" },
    ],
    completedAt: "2026-01-22T16:45:00Z",
  },
  vr4: {
    id: "vr4",
    solutionId: "s4",
    score: 88,
    checks: [
      { id: "c13", name: "Structure Validation", description: "Validates project directory structure and entry points", status: "pass" },
      { id: "c14", name: "Dependency Check", description: "Checks for outdated or vulnerable dependencies", status: "pass" },
      { id: "c15", name: "Secret Scan", description: "Scans for hardcoded secrets and credentials", status: "pass" },
      { id: "c16", name: "Environment Validation", description: "Validates environment configuration and variables", status: "fail", details: "Non-critical: optional env var missing" },
    ],
    completedAt: "2026-02-01T09:00:00Z",
  },
  vr5: {
    id: "vr5",
    solutionId: "s5",
    score: 95,
    checks: [
      { id: "c17", name: "Structure Validation", description: "Validates project directory structure and entry points", status: "pass" },
      { id: "c18", name: "Dependency Check", description: "Checks for outdated or vulnerable dependencies", status: "pass" },
      { id: "c19", name: "Secret Scan", description: "Scans for hardcoded secrets and credentials", status: "pass" },
      { id: "c20", name: "Environment Validation", description: "Validates environment configuration and variables", status: "pass" },
    ],
    completedAt: "2026-02-10T12:00:00Z",
  },
}

const reviews: Record<string, Review> = {
  r1: {
    id: "r1",
    solutionId: "s1",
    expertId: "e1",
    expertName: "Dr. Sarah Kim",
    decision: "approved",
    feedback: "Excellent implementation. Clean architecture, well-documented API endpoints, and comprehensive error handling. Ready for production use.",
    createdAt: "2026-01-18T09:00:00Z",
  },
  r2: {
    id: "r2",
    solutionId: "s5",
    expertId: "e1",
    expertName: "Dr. Sarah Kim",
    decision: "approved",
    feedback: "Outstanding Terraform modules with excellent documentation. Follows infrastructure-as-code best practices. Approved for catalog.",
    createdAt: "2026-02-12T15:00:00Z",
  },
}

export const mockSolutions: Solution[] = [
  {
    id: "s1",
    title: "React Auth Module",
    description: "A complete authentication module for React applications with JWT support, refresh tokens, role-based access control, and session management.",
    techStack: ["React", "TypeScript", "Node.js"],
    tags: ["authentication", "security", "frontend"],
    status: "approved",
    submittedBy: "u1",
    submittedByName: "Alex Rivera",
    sourceType: "github",
    sourceUrl: "https://github.com/alex/react-auth-module",
    validationReport: validationReports.vr1,
    review: reviews.r1,
    usageCount: 47,
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-01-18T09:00:00Z",
  },
  {
    id: "s2",
    title: "Python Data Pipeline",
    description: "Scalable ETL data pipeline framework built with Python, supporting multiple data sources and transformation stages with built-in monitoring.",
    techStack: ["Python", "PostgreSQL", "Docker"],
    tags: ["data", "etl", "pipeline", "backend"],
    status: "pending-review",
    submittedBy: "u2",
    submittedByName: "Jordan Chen",
    sourceType: "github",
    sourceUrl: "https://github.com/jordan/data-pipeline",
    validationReport: validationReports.vr2,
    usageCount: 0,
    createdAt: "2026-01-18T10:00:00Z",
    updatedAt: "2026-01-20T10:15:00Z",
  },
  {
    id: "s3",
    title: "Express API Boilerplate",
    description: "Quick-start Express.js API boilerplate with TypeScript, Prisma ORM, automated testing setup, and CI/CD pipeline configuration.",
    techStack: ["Node.js", "TypeScript", "Docker"],
    tags: ["api", "boilerplate", "backend"],
    status: "rejected",
    submittedBy: "u1",
    submittedByName: "Alex Rivera",
    sourceType: "zip",
    validationReport: validationReports.vr3,
    usageCount: 0,
    createdAt: "2026-01-20T14:00:00Z",
    updatedAt: "2026-01-22T16:45:00Z",
  },
  {
    id: "s4",
    title: "Vue Dashboard Components",
    description: "Collection of enterprise-ready Vue.js dashboard components including charts, data tables, KPI cards, and real-time data widgets.",
    techStack: ["Vue", "TypeScript"],
    tags: ["ui", "dashboard", "components", "frontend"],
    status: "pending-review",
    submittedBy: "u2",
    submittedByName: "Jordan Chen",
    sourceType: "github",
    sourceUrl: "https://github.com/jordan/vue-dashboard",
    validationReport: validationReports.vr4,
    usageCount: 0,
    createdAt: "2026-01-28T11:00:00Z",
    updatedAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "s5",
    title: "Terraform AWS Modules",
    description: "Production-ready Terraform modules for AWS infrastructure provisioning including VPC, ECS, RDS, and CloudFront configurations.",
    techStack: ["Terraform", "AWS", "Docker"],
    tags: ["infrastructure", "devops", "cloud"],
    status: "approved",
    submittedBy: "u1",
    submittedByName: "Alex Rivera",
    sourceType: "github",
    sourceUrl: "https://github.com/alex/terraform-aws",
    validationReport: validationReports.vr5,
    review: reviews.r2,
    usageCount: 31,
    createdAt: "2026-02-05T09:00:00Z",
    updatedAt: "2026-02-12T15:00:00Z",
  },
  {
    id: "s6",
    title: "GraphQL Gateway Service",
    description: "A federated GraphQL gateway that aggregates multiple microservices into a unified API layer with caching, rate limiting, and auth.",
    techStack: ["Node.js", "GraphQL", "TypeScript", "Redis"],
    tags: ["api", "gateway", "microservices"],
    status: "in-validation",
    submittedBy: "u2",
    submittedByName: "Jordan Chen",
    sourceType: "github",
    sourceUrl: "https://github.com/jordan/graphql-gateway",
    usageCount: 0,
    createdAt: "2026-02-20T14:00:00Z",
    updatedAt: "2026-02-20T14:00:00Z",
  },
  {
    id: "s7",
    title: "CI/CD Pipeline Templates",
    description: "Reusable CI/CD pipeline templates for GitHub Actions supporting build, test, deploy workflows for multiple languages and frameworks.",
    techStack: ["CI/CD", "Docker", "Kubernetes"],
    tags: ["devops", "automation", "cicd"],
    status: "in-validation",
    submittedBy: "u1",
    submittedByName: "Alex Rivera",
    sourceType: "snippet",
    codeSnippet: "name: Build and Deploy\non:\n  push:\n    branches: [main]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4",
    usageCount: 0,
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-02-25T10:00:00Z",
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "al1",
    action: "Solution Approved",
    performedBy: "e1",
    performedByName: "Dr. Sarah Kim",
    targetType: "solution",
    targetId: "s1",
    details: "React Auth Module approved after expert review",
    createdAt: "2026-01-18T09:00:00Z",
  },
  {
    id: "al2",
    action: "Solution Rejected",
    performedBy: "system",
    performedByName: "System",
    targetType: "solution",
    targetId: "s3",
    details: "Express API Boilerplate auto-rejected: validation score 55 below threshold",
    createdAt: "2026-01-22T16:45:00Z",
  },
  {
    id: "al3",
    action: "Expert Assigned",
    performedBy: "a1",
    performedByName: "Priya Patel",
    targetType: "solution",
    targetId: "s2",
    details: "Dr. Sarah Kim assigned to review Python Data Pipeline",
    createdAt: "2026-01-21T08:00:00Z",
  },
  {
    id: "al4",
    action: "Solution Approved",
    performedBy: "e1",
    performedByName: "Dr. Sarah Kim",
    targetType: "solution",
    targetId: "s5",
    details: "Terraform AWS Modules approved after expert review",
    createdAt: "2026-02-12T15:00:00Z",
  },
  {
    id: "al5",
    action: "User Created",
    performedBy: "system",
    performedByName: "System",
    targetType: "user",
    targetId: "u2",
    details: "New user Jordan Chen registered from TechCo",
    createdAt: "2025-11-01T10:30:00Z",
  },
  {
    id: "al6",
    action: "Solution Submitted",
    performedBy: "u2",
    performedByName: "Jordan Chen",
    targetType: "solution",
    targetId: "s6",
    details: "GraphQL Gateway Service submitted for validation",
    createdAt: "2026-02-20T14:00:00Z",
  },
  {
    id: "al7",
    action: "Force Revalidation",
    performedBy: "a1",
    performedByName: "Priya Patel",
    targetType: "solution",
    targetId: "s3",
    details: "Admin triggered revalidation for Express API Boilerplate",
    createdAt: "2026-02-22T09:30:00Z",
  },
]
